KnowledgeKernel/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('courses.urls')),
    path("accounts/",include('accounts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from .views import *
urlpatterns = [
     path('',homepage,name="home"),
     path('all-courses',allCourses,name="allCourses"),
     path('my-courses/',myCreatedCourse,name="myCreatedCourse"),
     path('about-course/<str:slug>',aboutCourse,name="about_course"),
     path('all-Tags/',allTags,name="allTags"),
     path ('search/',searchCourse,name= "searchCourse"),
     path ('category/<slug:slug>',viewCourseCategoriesWise,name= "viewCourseCategoriesWise"),
     #Course
     path('create-course/',createCourse,name="create_course"),
     path('update-course/<str:slug>/',updateCourse,name="updateCourse"),
     path('delete-course/<str:slug>/',deleteCourse,name="deleteCourse"),
     
     #Section
     path('create-section/<str:slug>/',CreateSectionCourse,name="create_section"),
     path('all-section/<str:slug>/',allSectionCourse,name="allSectionCourse"),
     path('update-section/course:<str:slug>/<str:section_slug>/<int:pk>',updateSection,name="update_section"),
     path('delete-section/course:<str:slug>/<str:section_slug>/<int:pk>',deleteSection,name="delete_section"),
     # path('update-section/course:<str:slug>/<str:section_slug>/',UpdateSectionCourse,name="update_section"),
     
     #Video
     path('all-section-video/<str:slug>/',allSectionVideo,name="allSectionVideo"),
     path('create-video/<str:slug>/',createSectionVideo,name="createSectionVideo"),
     path('create-video/<str:slug>/video-section=<str:section_slug>/<int:pk>/',createVideo,name="create_video"),
     path('update-video/<str:slug>/video-section=<str:section_slug>/<str:video_unique_id>/',updateVideo,name="update_video"),
     path('delete-video/<str:slug>/video-section=<str:section_slug>/<str:video_unique_id>/',deleteVideo,name="delete_video"),
     
     #Assessment
     path('all-assessment/<str:slug>/',allAssessment,name="allAssessment"),
     path('create-assessment/<str:slug>/',createAssessment,name="createAssessment"),
     path('update-assessment/course:<str:slug>/<int:pk>/',updateAssessment,name="updateAssessment"),
     path('delete-assessment/course:<str:slug>/<int:pk>/',deleteAssessment,name="deleteAssessment"),
     
     #Show Assessment
     path('assessment-course/<str:slug>/',showAllAssessment,name="showAllAssessment"),
     path('assessment-course/<str:slug>/assessment/<int:pk>/',submitAssessment,name="submitAssessment"),
     path('update-assessment-course/<str:slug>/assessment/<int:pk>/student-user/<int:student_user>/',updateAssessmentUser,name="updateAssessmentUser"),
     path('create-or-update-assessment-course/<str:slug>/assessment/<int:pk>/student-user/<int:student_user>/',submitOrUpdateAssessmentUser,name="submitOrUpdateAssessmentUser"),
     
     #marks
     path('submitted-user-course/<str:slug>/',showAllSubmittedAssessmentUser,name="showAllSubmittedAssessmentUser"),
     path('submitted-user-course/<str:slug>/search/',submittedUserSearch,name="submittedUserSearch"),
     path('course/<str:slug>/all-submitted-assessment/<str:student_user>/',showAllSubmittedAssessmentDetail,name="showAllSubmittedAssessmentDetail"),
     path('course/<str:slug>/mark-assessment/assessment/<int:assessment_pk>/submitted-assessment/<int:submitted_pk>/submitted-user/<int:student_user>/',markAssessment,name="markAssessment"),
     
     
     
     
     path('course/<slug:slug>/learn/lecture/<str:video_unique_id>/',courseDetail,name="courseDetail"),
]

courses/models.py
from django.db import models
from django.utils.text import slugify
from taggit.managers import TaggableManager
from accounts.models import UserProfile,Account
import uuid
from mptt.models import MPTTModel, TreeForeignKey
# from taggit.managers import TaggableManager# Create your models here.

class Category(MPTTModel):
    name = models.CharField(max_length=255)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    slug = models.SlugField(allow_unicode=True,max_length=100,unique=True)
    description =models.TextField(max_length=300,blank=True,null=True)
    created_at = models.DateTimeField(auto_now_add = True) 
    modified_at = models.DateTimeField(auto_now = True)     

    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        return  self.name
    
    
    def save(self,*args, **kwargs):
         if self.slug:
              self.slug = slugify(self.name ,allow_unicode=True)
         return super().save(*args, **kwargs)


class Course(models.Model):
    instructor = models.ForeignKey(UserProfile,on_delete=models.CASCADE) 
    name = models.CharField(max_length = 50 , null = False,unique = True)
    slug = models.CharField(max_length = 50 , null = False , unique = True)
    description = models.CharField(max_length = 700 , null = True)
    
    categories =models.ForeignKey(Category, on_delete=models.CASCADE )
    
    price = models.IntegerField(null=False,default=0)
    discount = models.IntegerField(null=False , default = 0) 
    
    active = models.BooleanField(default = False)
    thumbnail = models.ImageField( upload_to = "course/thumbnail") 
    
    created_at = models.DateTimeField(auto_now_add = True) 
    modified_at = models.DateTimeField(auto_now = True) 
    
    resource = models.FileField(upload_to = "course/resource",null=True,blank=True)
    length = models.IntegerField(null=False,default=0)
    
    tags = TaggableManager()
    prerequisite = models.CharField(max_length = 50 , null = True, blank=True,default="No need ")
    learning = models.CharField(max_length = 50 , null = False) 
    top_course = models.BooleanField(default=False)

    def __str__(self):
        return self.name
   
    def save(self,*args, **kwargs):
         if self.slug:
              self.slug = slugify(self.name ,allow_unicode=True)
         return super().save(*args, **kwargs)
     
     
# class CourseProperty(models.Model):
#     description  = models.CharField(max_length = 100 , null = False)
#     course = models.ForeignKey(Course , null = False , on_delete=models.CASCADE)

#     class Meta : 
#         abstract = True


# # class Tag(CourseProperty):
# #     pass
    
# class Prerequisite(CourseProperty):
#     pass

# class Learning(CourseProperty):
#     pass
class SectionVideo(models.Model):
    course = models.ForeignKey(Course , null = False , on_delete=models.CASCADE)
    name = models.CharField(max_length = 50 , null = False)
    slug = models.CharField(max_length = 50 , null = False )
    serial_number = models.IntegerField(null=False)
    
    def save(self,*args, **kwargs):
         if self.slug:
              self.slug = slugify(self.name)
         return super().save(*args, **kwargs)
     
    def __str__(self):
        return self.name
     


#Video
class Video(models.Model):
    section_video = models.ForeignKey(SectionVideo , null = False , on_delete = models.CASCADE)
    course = models.ForeignKey(Course , null = False , on_delete = models.CASCADE)
    title  = models.CharField(max_length = 100 , null = False)
    video_description = models.CharField(max_length = 500 , null = True)
    serial_number = models.IntegerField(null=False)
    video_id = models.CharField(max_length = 100 , null = False)
    resource = models.CharField( max_length=200,null=True,blank=True)
    resource_title = models.CharField(max_length=100,null=True,blank=True)
    is_preview = models.BooleanField(default = False)
    video_unique_id = models.CharField(max_length=100, blank=True, unique=True, default=uuid.uuid4)

    
    
    # def __init__(self):
    #      super(Video, self).__init__()
    #      self.video_unique_id = str(uuid.uuid4())
    # def __unicode__(self):
    #     return self.title
    

    def __str__(self):
        return f'course name: ({self.section_video.course}) --> section name: ({self.section_video}) --> video-title: {self.title}' 


class EnrolledCourse(models.Model):
     user = models.ForeignKey(Account, on_delete=models.CASCADE)
     course = models.ForeignKey(Course, on_delete=models.CASCADE)
     enrolled = models.BooleanField(default=True)
     created_at = models.DateTimeField(  auto_now_add=True)
     
     def __str__(self):
          return f'{self.user} course:{self.course} '
     

    
# Assessment
class Assessment(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title  = models.CharField(max_length = 100 , null = False)
    resource = models.CharField( max_length=200,null=False,blank=False)
    resource_title = models.CharField(max_length=100,default="Assessment")
    maximum_number  = models.IntegerField(null=False) 
    created_at = models.DateTimeField(auto_now_add = True) 
    modified_at = models.DateTimeField(auto_now = True) 
    
    def __str__(self):
        return f'course: ({self.course}) title: ({self.title})'


class SubmittedAssessment(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student_user = models.ForeignKey(EnrolledCourse, on_delete=models.CASCADE)
    assessment = models.ForeignKey(Assessment, on_delete=models.CASCADE)
    resource = models.CharField( max_length=200,null=False,blank=False)
    resource_title = models.CharField(max_length=100,null=False,blank=False)
    obtained_mark = models.IntegerField(default = 0)
    feedback = models.CharField( max_length=200,null=True,blank=True) 
    created_at = models.DateTimeField(auto_now_add = True) 
    modified_at = models.DateTimeField(auto_now = True) 
    
    def __str__(self):
        return f'{self.student_user}'

    # obtained = models.IntegerField(default =0)
    
class Mark(models.Model):
    assessment = models.ForeignKey(Assessment, on_delete=models.CASCADE)
    student_user = models.ForeignKey(Account, on_delete=models.CASCADE)
    student_submitted_assessment = models.ForeignKey(SubmittedAssessment, on_delete=models.CASCADE)
    obtained_mark = models.IntegerField(default = 0)
    feedback = models.CharField( max_length=200,null=True,blank=True) 
    
    # def __str__(self):
    #     return self.assessment
     
     

courses/forms.py
from django import forms
from .models import Course,SectionVideo,Video,Assessment,SubmittedAssessment,Mark
from taggit.models import Tag 
from courses.models import Category
class CourseCreateForm(forms.ModelForm):
   #  tags = forms.ModelMultipleChoiceField(label='Tags', queryset=Tag.objects.order_by('name'),widget=forms.SelectMultiple)
    tags = forms.ModelMultipleChoiceField(label='Tags', queryset=Tag.objects.order_by('name'),widget=forms.SelectMultiple)
    categories =  forms.ModelChoiceField(queryset=Category.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    
   #  tags = forms.CharField(queryset=Tag.objects.order_by('name'),widget=forms.SelectMultiple)
   #  active = forms.BooleanField(widget=forms.CheckboxInput (attrs={'class':'form-check-input','type':'checkbox'}))
    class Meta:
        model = Course
        fields = ["name","description","categories","price","discount","thumbnail","tags","resource","length","prerequisite","learning","active"]
        widgets = {
             'description' : forms.Textarea(attrs={'class':'form-control'}),

         } 
    def __init__(self, *args, **kwargs):
          super(CourseCreateForm, self).__init__(*args, **kwargs)
          self.fields['name'].widget.attrs['class'] = 'form-control'
          self.fields['description'].widget.attrs['class'] = 'form-control'
          self.fields['price'].widget.attrs['class'] = 'form-control'
          self.fields['length'].widget.attrs['class'] = 'form-control'
          self.fields['discount'].widget.attrs['class'] = 'form-control'
          self.fields['thumbnail'].widget.attrs['class'] = 'form-control'
          self.fields['resource'].widget.attrs['class'] = 'form-control'
          self.fields['prerequisite'].widget.attrs['class'] = 'form-control'
          self.fields['learning'].widget.attrs['class'] = 'form-control'
          self.fields['active'].widget.attrs['class'] = 'form-check-input'
         #  for field in self.fields:
         #       self.fields[field].widget.attrs['class'] = 'form-control'
          
  
class SectionForm(forms.ModelForm):
   
   class Meta:
      model = SectionVideo
      fields = ["name","serial_number"]
      widgets = {
             'name' : forms.TextInput(attrs={'class':'form-control'}),
         } 
   def __init__(self, *args, **kwargs):
          super(SectionForm, self).__init__(*args, **kwargs)
          self.fields['serial_number'].widget.attrs['class'] = 'form-control'
   def clean(self):
          cleaned_data = super(SectionForm, self).clean()
         #  password = cleaned_data.get('password')
         #  confirm_password = cleaned_data.get('confirm_password')
         
class VideoForm(forms.ModelForm):
   class Meta:
      model = Video
      fields = ["title","video_description","serial_number","video_id","resource","resource_title","is_preview"]
      
      widgets= {
         "video_description" : forms.Textarea()
      }
   def __init__(self, *args, **kwargs):
          super(VideoForm, self).__init__(*args, **kwargs)
          self.fields['title'].widget.attrs['class'] = 'form-control'
          self.fields['video_description'].widget.attrs['class'] = 'form-control'
          self.fields['serial_number'].widget.attrs['class'] = 'form-control'
          self.fields['resource'].widget.attrs['class'] = 'form-control'
          self.fields['resource_title'].widget.attrs['class'] = 'form-control'
          self.fields['video_id'].widget.attrs['class'] = 'form-control'
          self.fields['is_preview'].widget.attrs['class'] = 'form-check-input'

class AssessmentForm(forms.ModelForm):
   class Meta:
      model = Assessment
      fields = ['title','resource','resource_title','maximum_number']
   def __init__(self, *args, **kwargs):
         super(AssessmentForm, self).__init__(*args, **kwargs)
         self.fields['title'].widget.attrs['class'] = 'form-control'
       
         self.fields['resource'].widget.attrs['class'] = 'form-control'
         self.fields['resource_title'].widget.attrs['class'] = 'form-control'
         self.fields['maximum_number'].widget.attrs['class'] = 'form-control'
         
         
class SubmittedAssessmentForm(forms.ModelForm):
   class Meta:
      model = SubmittedAssessment
      fields = ['resource_title','resource']
   def __init__(self, *args, **kwargs):
         super(SubmittedAssessmentForm, self).__init__(*args, **kwargs)       
         self.fields['resource'].widget.attrs['class'] = 'form-control'
         self.fields['resource'].widget.attrs['placeholder'] = 'Resource link'
         self.fields['resource_title'].widget.attrs['class'] = 'form-control'
         
         
class MarkForm(forms.ModelForm):
   class Meta:
      model = SubmittedAssessment
      fields = ['obtained_mark','feedback']
      # fields = ['obtained_mark','feedback']
   def __init__(self, *args, **kwargs):
         super(MarkForm, self).__init__(*args, **kwargs)       
         self.fields['obtained_mark'].widget.attrs['class'] = 'form-control'
         self.fields['feedback'].widget.attrs['class'] = 'form-control'
   

templates/course/about-course.html
{% extends 'base.html' %}
{% load course_custom_tags %}

{% block title %}
{{course.name}}
{% endblock title %}

{% block content %}

<div class="container">
     <h1><b> {{course.name}} </b> </h1>
     <div class="row">
          <div class="col-md-9">
               <img src="{{course.thumbnail.url}}" height = "500px" width="820px"  alt="">
               <h3>
                    <b>About Course:</b><br>
                    {{course.description}}
               </h3>
               <div class="col">
                    <ul id='video_list' class="list-group overflow-scroll">

                         {% for item in sections %}
                         {% comment %} {{video_youtube.section_video}} {% endcomment %}
                         <div id="my-scope-{{item}}" class=" wrapper 
                         {% if video_youtube.section_video == item %}
                         
                         {% else %}
                         collapsed 
                         {% endif %}
                         ">
                              <div class="activator" onclick="toogleSelection('my-scope-{{item}}')">
                                   {{item}}
                              </div>
                              {% for video in item.video_set.all  %}
                              {% comment %} {{video.video_id}} {% endcomment %}
                              <div class="content  ">
                                   {% if video.is_preview  is False %}


                                   <div
                                        class=" {% if video.video_unique_id ==  video_youtube.video_unique_id %} active-video {% else %} block {% endif %} ">
                                        {{video.serial_number}}.{{video.title}}
                                   </div>


                                   {% else %}

                                   <a href=" {% url 'courseDetail' course.slug video.video_unique_id  %}">
                                        <div
                                             class=" {% if video.video_unique_id ==  video_youtube.video_unique_id %} active-video {% else %} block {% endif %} ">
                                             {{video.serial_number}}.{{video.title}}
                                        </div>

                                   </a>
                                   {% endif %}
                              </div>
                              {% if video.resource  %}
                              <div class="content  ">
                                   <div
                                        class="{% if video.serial_number ==  video_youtube.serial_number %} active-video {% else %} block {% endif %} ">
                                        <a class="nav-link dropdown-toggle" href="#" role="button"
                                             data-bs-toggle="dropdown" aria-expanded="false">
                                             Download Resources
                                        </a>

                                        <ul class="dropdown-menu">
                                             <li>
                                                  <a class="dropdown-item" target="_blank" href="{{video.resource}}">

                                                       {% if video.resource_title %}

                                                       {{video.resource_title}}

                                                       {% else %}
                                                       Resources
                                                       {% endif %}

                                                  </a>
                                             </li>

                                        </ul>
                                   </div>

                              </div>
                              {% endif %}
                              {% endfor %}
                         </div>
                         {% endfor %}




                         {% comment %} {% for  video in videos %}
                         <a href="?lecture={{video.serial_number}}">
                              <li class="list-group-item {% if video == video_youtube %} active {% endif %} "
                                   aria-current="true">
                                   {{video.serial_number}}.{{video.title}}
                              </li>
                         </a>
                         {% endfor %} {% endcomment %}
                    </ul>


               </div>
          </div>
          <div class="col-md-3">
               <h4><b>This course includes:</b></h4>
               <h5>Price: {{course.price}} </h5>
               <h5>Discount: {{course.discount}} </h5>
               <h5>Tags: <ul>

                         {% for tag in course.tags.all %}

                         <li>
                              {{tag}}
                         </li>
                         {% endfor %}

                    </ul>
               </h5>
               <h5>Length: {{course.length}} hours on-demand video</h5>

          </div>

     </div>
</div>

{% endblock %}

templates/course/all-courses.html
{% extends 'base.html' %}
{% load course_custom_tags %}

{% block title %}
All Courses
{% endblock title %}

{% block content %}
<div class="container mt-4 ">
     <div class="container">

          <form action="{% url 'searchCourse' %}" class="form-inline p-3 d-flex justify-content-center ">
               <input class="form-control  mx-5" type="search" placeholder="Search Course" aria-label="Search" name="keyword">
               <button class="btn btn-outline-success my-2 my-sm-0 " type="submit">Search</button>
          </form>
     </div>
     <div class="container mt-3 ">
          <h2><a href="{% url 'allCourses' %}">All Courses</a> </h2>
          <h2>
               Course:     
               <b>
          {% if 'categor' in request.path %}
               {{category}}
               
          {% endif %}</b></h2>
          Total Courses: <b>{{courses_count}}</b>
          <div class="row mt-5">
               {% for course in courses %}

               <div class="col mx-auto mb-3">
                    <div class="card mx-auto" style="width: 18rem; height:500px">
                         <img style=" height:400px" src="{{course.thumbnail.url}}" class="card-img-top" alt="...">
                         <div class="card-body">
                              <b>
                                   <h4 class="card-title">{{course.name}}</h4>
                              </b>
                              {% comment %} {{course.video_set.all.0.video_unique_id}} {% endcomment %}
                              <p class="card-text">
                                   Save: <b>
                                        {{course.discount}}%
                                   </b>
                                   <br>
                                   <span class="fs-5">
                                        Price: <del>{{course.price|dollar}}</del>
                                        &nbsp;

                                        <span>{% course_sell_price course.price course.discount as value %}
                                             {{value|dollar}}
                                        </span>
                                   </span>

                              </p>



                              <div class="row mt-3 ">
                                   <div class="col ">
                                        <a class="btn btn-primary btn-block" href="">Enroll Now</a>
                                   </div>
                                   <div class="col">
                                        <a class="btn btn-info btn-block"
                                             href="{% url 'about_course' course.slug %}">Show
                                             More</a>
                                   </div>
                              </div>


                         </div>
                    </div>
               </div>

               {% endfor %}


          </div>

     </div>
</div>
{% endblock %}

templates/course/all-section-video.html
{% extends 'base.html' %}
{% load course_custom_tags %}

{% block title %}
All Video
{% endblock title %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg mb-3">

     <div class="container mt-2">
          {% include 'includes/alerts.html' %}
          <div class="row">
               {% include 'includes/dashboard_sidebar_course.html' %}
               <main class="col-md-9">
                    <article class="card">

                         <header class="card-header">
                              <strong class="d-inline-block mr-3">
                                   All Videos
                              </strong>
                         </header>
                         <div class="card-body">
                              <div class="row">
                                   <div class="col-md-12">
                                        <div class="card" style="text-align:center">
                                             <div class="card-body">
                                                  <h5 class="card-title">
                                                       Total Videos : <b>{{count}}</b>
                                                  </h5>

                                             </div>

                                        </div>
                                        <div class="mt-4">


                                             <ul id='video_list' class="list-group">



                                                  {% for section in sections %}
                                                  <div id="my-scope-{{section.slug}}" class=" wrapper collapsed">
                                                       <div class="activator"
                                                            onclick=" toogleSelection('my-scope-{{section.slug}}')">
                                                            {{section}}
                                                       </div>
                                                       {% comment %} {{video.video_id}} {% endcomment %}


                                                       {% for video in section.video_set.all  %}

                                                       <div class="content float-left ">
                                                            <div class=" block ">
                                                                 {{video.serial_number}} : {{video.title}} 
                                                                 
                                                                      {% if video.is_preview %}
                                                                          <p>(have preview)</p> 
                                                                      {% endif %}
                                                                 
                                                                 <div class=" container  mt-2">

                                                                      <a href="{% url 'update_video' course.slug section.slug video.video_unique_id   %}">
                                                                           <button class="btn btn-primary">Edit</button>
                                                                      </a>
                                                                      <a href="{% url 'delete_video' course.slug section.slug video.video_unique_id   %}">
                                                                           <button class="btn btn-danger">Delete</button>
                                                                      </a>
                                                                      
                                                                      
                                                                 </div>
                                                            </div>
                                                       </div>


                                                       {% endfor %}
                                                  </div>

                                             </ul>
                                        </div>


                                        {% endfor %}

                                        </ul>


                                   </div>


                              </div>

                         </div> <!-- row.// -->
          </div> <!-- card-body .// -->



          </article> <!-- order-group.// -->
          </main>
     </div> <!-- row.// -->
     </div>


</section>
{% endblock %}

templates/course/all-tags.html
{% extends 'base.html' %}
{% load course_custom_tags %}
{% block title %}
All Tags
{% endblock title %}
{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg mb-3">
     {% include 'includes/alerts.html' %}
     <div class="container mt-2">
          <div class="row">
               {% include 'includes/dashboard_sidebar.html' %}
               
               <main class="col-md-9">
                    <article class="card">

                         <header class="card-header">
                              <strong class="d-inline-block mr-3">
                                   Show All Tags
                              </strong>
                         </header>
                         <div class="container">
                              <ol>
                                   
                                   {% for tag in tags %}
                                        
                                   
                                   <li>
                                        {{tag}}
                                   </li>
                                   {% endfor %}
                              </ol>

                         </div>
                    </article> <!-- order-group.// -->
               </main>
          </div> <!-- row.// -->
     </div>


</section>


<script>
     $(document).ready(function () {

          var multipleCancelButton = new Choices('#id_tags', {
               removeItemButton: true,
               maxItemCount: 5,
               searchResultLimit: 5,
               renderChoiceLimit: 5
          });

     });
</script>


{% endblock %}

templates/course/delete-course.html
{% extends 'base.html' %}
{% load course_custom_tags %}
{% block title %}
Delete Course
{% endblock title %}
{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg mb-3">
     {% include 'includes/alerts.html' %}
     <div class="container mt-2">
          <div class="row">
                    {% include 'includes/dashboard_sidebar_course.html' %}
                    
               <main class="col-md-9">
                    <article class="card">

                         <header class="card-header bg-danger">
                              <strong class="d-inline-block mr-3">
                                   Delete Course : {{course}}

                              </strong>
                         </header>
                         <div class="container  ">

                              <br>
                              <h2>Do you want to delete <br>
                                   Course: <b class="text-danger">{{course}}</b>
                                    </h2>
                              <br>
                              <form method="post">
                                   {% csrf_token %}
                                   <button type="submit" class="btn btn-danger mb-3">Delete</button>

                              </form>
                         </div>
                    </article> <!-- order-group.// -->
               </main>
          </div> <!-- row.// -->
     </div>


</section>



{% endblock %}